const data = [
    {
        id:1,
        name:"Cherry",
        image:"/Cherry.JPG",
        yourBalance:7,
        friendBalance:0,
        selectedFriend:{
            id:1,
            select:false
        },
        selectedPayers:{
            payer1:"you",
            payer2:"Cherry"
        }
    },
    {
        id:2,
        name:"Sathi",
        image:"/Sathireddy.JPG",
        yourBalance:0,
        friendBalance:20,
        selectedFriend:{
            id:2,
            select:false
        },
        selectedPayers:{
            payer1:"you",
            payer2:"Sathi"
        }
    },
    {
        id:3,
        name:"Rajyam",
        image:"/Rajam.JPG",
        yourBalance:0,
        friendBalance:0,
        selectedFriend:{
            id:3,
            select:false
        },
        selectedPayers:{
            payer1:"you",
            payer2:"Rajyam"
        }
    }
];
export default data;